aScienceWebsite/aScienceWebsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('project/', include('project.urls')),
    path('admin/', admin.site.urls),
]

aScienceWebsite/project/urls.py
from django.urls import path
from . import views

app_name = 'project'

urlpatterns = [
    # /project
    path('', views.index, name='index'),


    # /project/<project_id>/
    path('<int:project_id>', views.detail, name='detail'),

    # /project/<project_id>/favorite
    #path('<int:project_id>/favorite', views.favorite, name='favorite'),

]

aScienceWebsite/project/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=300) #Name of the project
    team_leader = models.CharField(max_length=250) #Leader of the team
    content = models.TextField() #One field for the content of the project


    ##This function will return additional information when looking for data
    def __str__(self):
        return self.name + ' - ' + self.team_leader


class Image(models.Model): #This table will contain the content of the projects
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    name = models.CharField(max_length=400)   #Name or location of the image
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.name

aScienceWebsite/project/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from .models import Project, Image


# Create your views here.

def index(request):
    all_projects = Project.objects.all() #Stores the result of the db call
    context = {'all_projects': all_projects} #Information tha the template needs
    return  render(request, 'project/index.html', context) #The HttpResponse is built in this render


def detail(request, project_id):
    #project = Project.objects.get(pk=project_id)
    project = get_object_or_404(Project, pk=project_id)
    return render(request, 'project/detail.html', {'project': project})

def favorite(request, project_id):
    #project = Project.objects.get(pk=project_id)
    project = get_object_or_404(Project, pk=project_id)
    return render(request, 'project/detail.html', {'project': project})

aScienceWebsite/project/templates/project/detail.html
{% load staticfiles  %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">﻿
<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'project/style.css'%}">

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Logo -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'project:index' %}">A Science Website</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="nav navbar-nav">
                    <a href="{% url 'project:index' %}">
                        <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>&nbsp;
                        About us
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

        </div>
    </div>
</nav>

<h1>{{project.name}}</h1>
<h2>{{project.team_leader}}</h2>
<h3>{{project.content}}</h3>

<!--<ul>
    {% for image in project.image_set.all %}
    <li>{{image.name}}</li>
    {% endfor %}
</ul> -->

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'project:detail' project.id %}" method="post">
    {% csrf_token %}
    {%  for image in project.image_set.all %}
   <input type="radio" id="image{{ forloop.counter }}" name="image" value="{{ name.id }}">
    <label for="image{{ forloop.counter }}" >
       {% static "" as baseUrl %}
        <!--<img src="{{ baseUrl }}/project/images/{{image.name}}">-->
       <img src="{% static "project/images/ocean1.jpeg" %}" alt="Image Description">
    </label>  <br>
    {% endfor %}
</form>

aScienceWebsite/project/templates/project/index.html
<!--Loads the path to the static files-->
{% load staticfiles  %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">﻿
<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'project/style.css'%}">

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Logo -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'project:index' %}">A Science Website</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="nav navbar-nav">
                    <a href="{% url 'project:index' %}">
                        <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>&nbsp;
                        About us
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

        </div>
    </div>
</nav>


{% if all_projects %}
    <h3> Here are all my Projects </h3>
    <ul>
        {% for project in all_projects %}
            <li><a href="{% url 'project:detail' project.id %}">{{project.name}}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <h3> You don't have any project</h3>

{% endif %}